-   become: true
    block:

    -   name: Ensure acl is installed
        apt:
            name: acl
            state: latest
            update_cache: true

    -   name: Skip setting up Oh My Zsh if ".zshrc" already exists
        stat:
            path: "/home/{{ username }}/.zshrc"
        register: zshrc_stat

    -   name: Download Oh My Zsh install script
        get_url:
            url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
            dest: /tmp/zsh-installer.sh
            mode: 0755
        become_user: "{{ username }}"
        when: zshrc_stat.stat.exists == false

    -   name: Run Oh My Zsh install script for user "{{ username }}"
        command: /bin/sh /tmp/zsh-installer.sh --unattended
        become_user: "{{ username }}"
        when: zshrc_stat.stat.exists == false

    -   name: Download zsh-syntax-highlighting plugin
        become_user: "{{ username }}"
        git:
            repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
            dest: "/home/{{ username }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
            clone: yes
            update: yes
            depth: 1

    -   name: Download zsh-autosuggestions plugin
        become_user: "{{ username }}"
        git:
            repo: https://github.com/zsh-users/zsh-autosuggestions
            dest: "/home/{{ username }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
            clone: yes
            update: yes
            depth: 1

    -   name: Copy custom zshrc for user "{{ username }}"
        copy:
            src: zshrc
            dest: "/home/{{ username }}/.zshrc"
            owner: "{{ username }}"
            group: "{{ username }}"
            mode: 0644
            force: true

    -   name: Cleanup bash config files
        file:
            path: "/home/{{ username }}/{{ item }}"
            state: absent
        loop:
            - .bashrc_history
            - .bash_logout
            - .bashrc
            - .profile
            - .zshrc.pre-oh-my-zsh
