version: '3'

services:

    app:
        build:
            context: ./resources/docker/8.1
            dockerfile: Dockerfile
            args:
#                WWWGROUP: '${WWWGROUP}'
                XDEBUG: '${SAIL_XDEBUG:-false}'
                XDEBUG_PORT: '${SAIL_XDEBUG_PORT:-9003}'
        image: michman-8.1/app
        ports:
            - '80:8000'
        volumes:
            - '.:/var/www/html'
        depends_on:
            - redis
            - mysql
        restart: unless-stopped

    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - 'redis-data:/data'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]

    mysql:
        image: 'mysql:8.0'
        platform: 'linux/x86_64'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'mysql-data:/var/lib/mysql'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping"]

    websockets:
        image: michman-8.1/app
        command: 'php artisan websockets:serve'
        volumes:
            - '.:/var/www/html'
        ports:
            - '6001:6001'
        depends_on:
            - redis
            - mysql

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '1025:1025'
            - '8025:8025'

#    meilisearch:
#        image: 'getmeili/meilisearch:latest'
#        ports:
#            - '7700:7700'
#        volumes:
#            - 'meilisearch-data:/data.ms'

volumes:
    redis-data:
        driver: local
    mysql-data:
        driver: local
