version: '3'

services:

    app:
        # To reuse the whole base app service for other services, see below.
        &app-image
        build:
            context: ./resources/docker/8.1
            dockerfile: Dockerfile
            args:
#                WWWGROUP: '${WWWGROUP}'
                XDEBUG: '${SAIL_XDEBUG:-false}'
                XDEBUG_PORT: '${SAIL_XDEBUG_PORT:-9003}'
        image: michman-8.1/app
        ports:
            - '80:8000'
        volumes:
            - '.:/var/www/html'
        depends_on:
            - redis
            - mysql

    queue:
        <<: *app-image
        command: [
            "php", "artisan", "queue:work",
            "--queue", "default,providers,servers,broadcasting",
            "--sleep", "3",
            "--tries", "3",
            "--timeout", "300",
            "--backoff", "5",
            "--memory", "256"
        ]
        ports: []

    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - 'redis-data:/data'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]

    mysql:
        image: 'mysql:8.0'
        platform: 'linux/x86_64'
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            APP_DATABASE: '${DB_DATABASE}'
            APP_USER: '${DB_USERNAME}'
            APP_PASSWORD: '${DB_PASSWORD}'
            TELESCOPE_DATABASE: '${TELESCOPE_DB_DATABASE}'
            TELESCOPE_USER: '${TELESCOPE_DB_USERNAME}'
            TELESCOPE_PASSWORD: '${TELESCOPE_DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'mysql-data:/var/lib/mysql'
            - './resources/docker/mysql/init.sh:/docker-entrypoint-initdb.d/init.sh'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping"]

    websockets:
        <<: *app-image
        command: 'php artisan websockets:serve'
        ports:
            - '8080:6001'
        depends_on:
            - redis
            - mysql

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '1025:1025'
            - '8025:8025'

#    meilisearch:
#        image: 'getmeili/meilisearch:latest'
#        ports:
#            - '7700:7700'
#        volumes:
#            - 'meilisearch-data:/data.ms'

volumes:
    redis-data:
        driver: local
    mysql-data:
        driver: local
