-   become: true
    block:

    -   name: Upload sshd_config
        copy:
            src: sshd_config
            dest: /etc/ssh/sshd_config
            owner: root
            group: root
            mode: 0644
        notify:
            - restart sshd
