#

# TODO: VERY IMPORTANT! Queue worker can easily make MySQL use 100% of available CPU when performing some heavy SQL queries.
#       Should make sure the app can still work while at it and it cannot be abused.

# Reusable logging config
x-logging:
    &default-logging
    driver: "local"



services:

    nginx:
        image: nginx:1.21-alpine
        user: nginx
        command: ["nginx", "-g", "daemon off;"]
        read_only: true
        networks:
            - backend
        ports:
            - '443:4443'
        volumes:
            # Public static assets
            - 'app-public:/home/app/michman/public:ro'
            # General config
            - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
            - './nginx/gzip.conf:/etc/nginx/gzip.conf:ro'
            - './nginx/mime.types:/etc/nginx/mime.types:ro'
            - './nginx/fastcgi_params:/etc/nginx/fastcgi_params:ro'
            # Staging-specific
            - './nginx/stage/app.conf:/etc/nginx/conf.d/app.conf:ro'
            - './nginx/stage/websockets.conf:/etc/nginx/conf.d/websockets.conf:ro'
            # SSL key
            - './michman.dev.crt:/etc/nginx/michman.dev.crt:ro'
            # Disposable volumes for temporary files
            - /var/cache
            - /var/run
            - /tmp
        depends_on:
            - app
        restart: unless-stopped
        logging: *default-logging

    # Example commands to build and push this image:
    # docker image build --platform linux/amd64 -t kondorb/michman:XXX --build-arg APP_VERSION=XXX --build-arg SPARK_USERNAME=YYY --build-arg SPARK_PASSWORD=ZZZ .
    # docker image push kondorb/michman:XXX
    app:
        # To reuse the whole base app service for other services, see below.
        &app-image
        image: kondorb/michman:0.9.5
        platform: 'linux/amd64'
        read_only: true
        environment:
            APP_ENV: stage
        networks:
            - backend
        volumes:
            - 'app-public:/home/app/michman/public:ro'
            - './.env.stage:/home/app/michman/.env.stage:ro'
        restart: unless-stopped
        logging: *default-logging
        healthcheck:
            test: ["CMD", "php", "artisan", "version"]

    queue:
        <<: *app-image
        command: ["php", "artisan", "horizon"]
        # This should be at least as long as the longest job is allowed to run.
        stop_grace_period: 30m

    scheduler:
        <<: *app-image
        command: ["php", "artisan", "schedule:work"]

    websockets:
        <<: *app-image
        command: [
            "php", "artisan", "websockets:serve",
            "--port", "6001",
            "--host", "0.0.0.0",
        ]



volumes:
    # Application public directory with static assets.
    app-public:
        driver: local



networks:
    backend:
        external: true
        name: michman-stage_backend-network
