-   become: true
    block:

    -   name: Install zsh
        apt: name=zsh state=latest update_cache=true

    -   name: Create user "{{ username }}" for manual access
        user:
            name: "{{ username }}"
            shell: /usr/bin/zsh
            groups: adm,sudo
            append: true

    -   name: Set a random password when creating this user
        user:
            name: "{{ username }}"
            password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') | password_hash('sha512') }}"
            update_password: on_create

    -   name: Set user password if provided
        when: user_password is defined
        user:
            name: "{{ username }}"
            password: "{{ user_password | password_hash('sha512') }}"

    -   name: "Install packages I'm used to"
        apt:
            name:
                - tmux
                - ruby
                - rsync
                - curl
                - git
            state: latest
            update_cache: true

    -   name: Install rmate
        gem:
            name: rmate
            state: latest

    -   name: Copy custom tmux config
        copy:
            src: tmux.conf
            dest: "/home/{{ username }}/.tmux.conf"
            owner: "{{ username }}"
            group: "{{ username }}"
            mode: 0644
            force: true

    -   name: Add an SSH key for manual access
        authorized_key:
            user: "{{ username }}"
            key: "{{ lookup('file', manual_ssh_public_key) }}"
