-   become: true
    block:

    -   name: Get Linux kernel compilation options
        command: cat /boot/config-{{ ansible_kernel }}
        register: kernel_config
        changed_when: false

    -   name: Check if Linux kernel is compiled with TCP BBR options (as a module or builtin)
        set_fact:
            bbr_supported: kernel_config.stdout is search("CONFIG_TCP_CONG_BBR=[my]") and kernel_config.stdout is search("CONFIG_NET_SCH_FQ=[my]")

    -   name: Enable fq qdisc traffic pacing for BBR
        when: bbr_supported
        sysctl:
            name: net.core.default_qdisc
            value: fq
            sysctl_set: yes
            state: present
            reload: yes

    -   name: Enable fq qdisc traffic pacing for BBR
        when: bbr_supported
        sysctl:
            name: net.ipv4.tcp_congestion_control
            value: bbr
            sysctl_set: yes
            state: present
            reload: yes
