-   become: true
    block:

    -   name: Install packages required for Docker installation
        apt:
            name:
                - gnupg
                - curl
                - python3
                - python3-pip
                - python3-docker
                - virtualenv
                - apt-transport-https
            state: latest
            update_cache: true

    -   name: Add Docker GPG apt key
        apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

    -   name: Add Docker repo to apt
        apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable
            state: present

    -   name: Install docker-ce
        apt:
            name: docker-ce
            state: latest
            update_cache: yes

    -   name: Ensure Docker service is running
        service:
            name: docker
            state: started

    -   name: Add "ansible" user to "docker" group
        user:
            user: ansible
            groups: docker
            append: true

    -   name: Download docker-compose utility
        get_url:
            url: "https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-{{ ansible_facts['system'] }}-{{ ansible_facts['architecture'] }}"
            dest: /usr/local/bin/docker-compose
            owner: root
            group: root
            mode: 0755

    -   name: Download docker-compose utility using pip
        pip:
            executable: pip3
            name: docker-compose
