-   hosts: homeserver
    become: true
    tasks:

    -   name: Update apt cache
        apt: update_cache=true
        changed_when: false

    -   name: Install required packages
        apt:
            name:
                - acl
                - gnupg
                - ca-certificates
                - curl
                - lsb-release
                - python3
                - python3-pip
                - virtualenv
                - apt-transport-https
                - ufw
            state: latest
            update_cache: true

    -   name: Install and configure UFW
        include_role: name=configure-ufw

#     -   name: Configure sshd
#         include_role: name=configure-sshd

    -   name: Install Docker
        include_role: name=install-docker
        vars:
            compose_version: "1.29.2"

    -   name: Enable TCP BBR if supported
        include_role: name=enable-tcp-bbr

#    -   name: "UFW: Allow HTTP/HTTPS traffic"
#        ufw:
#            direction: in
#            port: "{{ item }}"
#            rule: allow
#        loop:
#            - '80'
#            - '443'
