all:
    children:
        production:
            hosts:
                michman-app-1:
                    ansible_host: 167.99.217.206
        staging:
            hosts:
                michman-staging:
                    ansible_host: 176.124.200.69
    vars:
        ansible_port: 22
        ansible_user: ansible
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_private_key_file: ~/.ssh/id_ansible
