all:
    children:
        prod:
            hosts:
                michman-app-1:
                    ansible_host: 176.124.213.171
        stage:
            hosts:
                michman-stage:
                    ansible_host: 176.124.200.69
        dev:
            hosts:
                michman-dev:
                    ansible_host: 176.124.217.190
    vars:
        ansible_port: 22
        ansible_user: ansible
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_private_key_file: ~/.ssh/id_ansible
