all:
    children:
        app_servers:
            hosts:
                michman-app-1:
                    ansible_host: 167.99.217.206
        staging:
            hosts:
                michman-stage:
                    ansible_host: 64.227.72.39
    vars:
        ansible_port: 22
        ansible_user: ansible
        ansible_python_interpreter: /usr/bin/python3
