all:
    children:
        prod:
            hosts:
                michman-app-1:
                    ansible_host: 159.223.223.15
    vars:
        ansible_port: 22
        ansible_user: ansible
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_private_key_file: ~/.ssh/id_ansible
