-   hosts: stage
    become: true
    tasks:

    -   name: Down the whole Docker Compose project
        docker_compose:
            project_src: &project_src /home/michman/michman
            files: &files docker-compose.stage.yaml
            project_name: &project_name michman-stage
            state: absent

    -   name: Remove the volume with public assets
        docker_volume:
            name: michman-stage_app-public
            state: absent

    -   name: Update stage Docker Compose config
        synchronize:
            src: ../../deployment/
            dest: /home/michman/michman
            archive: false
            recursive: true
            checksum: true
            delete: true

    -   name: Chown Docker Compose config files
        file:
            path: /home/michman/michman
            state: directory
            recurse: yes
            owner: michman
            group: michman

    -   name: Login to Docker Hub
        when: (docker_username is defined) and (docker_password is defined)
        docker_login:
            username: "{{ docker_username }}"
            password: "{{ docker_password }}"

#  TODO: Add a step with docker-compose yaml files validation using "docker-compose config"

    -   name: Deploy Docker Compose project
        docker_compose:
            project_src: *project_src
            files: *files
            project_name: *project_name
            build: false
            pull: true
            recreate: always
            remove_orphans: true
        register: output

    -   name: Print output
        debug: var=output
